author: Colby Terry - VoidTeam Network
database: false
description: "Promotes players automatically based on their mcMMO Skills.\r\n"
main: net.voidteam.plugins.mcmmosp.McMMOSkillPromote
name: mcMMOSkillPromote
startup: postworld
version: '0.2'

commands:
    mcmmosp:
      description: Information about the plugin.
      usage: /<command> info

permissions:
    mcmmosp.reload:
        description: Allows you to reload the config.
        default: op
    mcmmosp.refresh:
        description: Refreshes and adds specified player to the groups they qualify for.
        default: op